/**
 * A set of rules for JavaScript.
 *
 * @type {import("eslint").Linter.Config}
 */
export const javascriptConfig = [
  {
    rules: {
      "prefer-object-spread": "error",
      "prefer-arrow-callback": "error",
      "prefer-template": "error",
      "array-callback-return": "error",
      "no-await-in-loop": "error",
      "no-constructor-return": "error",
      "no-inner-declarations": "error",
      "no-promise-executor-return": "error",
      "no-self-compare": "error",
      "no-template-curly-in-string": "error",
      "no-unmodified-loop-condition": "error",
      "no-unreachable-loop": "error",
      "no-unused-private-class-members": "error",
      "no-use-before-define": "error",
      "require-atomic-updates": "error",
      "block-scoped-var": "error",
      "consistent-return": "error",
      "accessor-pairs": "error",
      "default-case": "error",
      "default-case-last": "error",
      eqeqeq: "error",
      "guard-for-in": "error",
      "no-alert": "error",
      "no-caller": "error",
      "no-continue": "error",
      "no-else-return": "error",
      "no-eq-null": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-implicit-coercion": "error",
      "no-implied-eval": "error",
      "no-empty": "error",
      "no-empty-function": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-multi-assign": "error",
      "no-multi-str": "error",
      "no-nested-ternary": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-object": "error",
      "no-new-wrappers": "error",
      "no-octal-escape": "error",
      "no-param-reassign": "error",
      "no-proto": "error",
      "no-return-assign": "error",
      "no-return-await": "error",
      "no-self-assign": "error",
      "no-plusplus": "error",
      "no-redeclare": "error",
      "no-restricted-properties": "error",
      "no-useless-call": "error",
      "no-useless-catch": "error",
      "no-useless-concat": "error",
      "no-useless-return": "error",
      radix: "error",
    },
  },
];
